<?php

/**
 * @file
 * Primary module hooks for Galicloud Theming module.
 */




/**
 * Implements hook_theme().
 */
function galicloud_theming_theme($existing, $type, $theme, $path)
{
  return [
    'galicloud_theming_dimensions' => [
      'variables' => [
        'length' => NULL,
        'width' => NULL,
        'height' => NULL,
        'unit' => 'cm.'
      ],
      'template' => 'galicloud-theming-dimensions',
    ],
  ];

}


/**
 * Implements hook_preprocess_HOOK().
 */
//function galicloud_theming_preprocess_galicloud_theming_dimensions(&$variables)
//{
//  $variables['#attached']['library'][] = 'galicloud_theming/global';
//
//}

/**
 * Implements hook_preprocess_HOOK().
 */
function galicloud_theming_preprocess_page(&$variables)
{
  $variables['page']['#cache']['contexts'][] = 'route';
  if (\Drupal::routeMatch()->getRouteName() === 'galicloud_theming.render') {
    $variables['#attached']['library'][] = 'galicloud_theming/global';
  }
}


function galicloud_theming_theme_suggestions_galicloud_theming_dimensions_alter(array &$suggestions, array $variables)
{
  if (\Drupal::currentUser()->isAuthenticated()) {
    $suggestions[] = 'galicloud_theming_dimensions__logged_in';
  }
}
