<?php

namespace Drupal\galicloud_blocks\Form;

use Drupal\Core\Database\Connection;
use Drupal\Core\Form\FormBase;
use Drupal\Core\Form\FormStateInterface;
use Drupal\Core\Routing\RouteMatchInterface;
use Drupal\Core\Session\AccountInterface;
use Symfony\Component\DependencyInjection\ContainerInterface;

/**
 * Provides a Galicloud blocks form.
 */
class NodeVotingForm extends FormBase
{
  protected Connection $database;
  protected AccountInterface $currentUser;
  protected RouteMatchInterface $currentRouteMatch;

  public function __construct(Connection $database, AccountInterface $currentUser, RouteMatchInterface $current_route_match)
  {
    $this->database = $database;
    $this->currentUser = $currentUser;
    $this->currentRouteMatch = $current_route_match;
  }

  public static function create(ContainerInterface $container)
  {
    //return parent::create($container); // TODO: Change the autogenerated stub
    return new static(
      $container->get('database'),
      $container->get('current_user'),
      $container->get('current_route_match')
    );
  }


  /**
   * {@inheritdoc}
   */
  public function getFormId()
  {
    return 'galicloud_blocks_node_voting';
  }

  /**
   * {@inheritdoc}
   */
  public function buildForm(array $form, FormStateInterface $form_state)
  {

    $node_vote = null;
    $node = $this->currentRouteMatch->getParameter('node');

    $nid = $node ? $node->id() : null;

    if ($nid && $this->currentUser->isAuthenticated()) {
      $node_vote = $this->database->select('galicloud_node_votes', 'f')
        ->fields('f', ['vote'])
        ->condition('f.nid', $nid)
        ->condition('f.uid', $this->currentUser->id())
        ->execute()
        ->fetchField();

      $form['node_vote'] = [
        '#type' => 'radios',
        '#title' => $this->t('Vote this node'),
        '#options' => [1 => 1, 2 => 2, 3 => 3, 4 => 4, 5 => 5],
        '#description' => $this->t('How useful did you find this content?'),
        '#required' => TRUE,
        '#default_value' => $node_vote,
      ];

      $form['nid'] = [
        '#type' => 'value',
        '#value' => $nid,
      ];

      $form['uid'] = [
        '#type' => 'value',
        '#value' => $this->currentUser->id(),
      ];

      $form['submit'] = [
        '#type' => 'submit',
        '#value' => $this->t('Vote'),
      ];

      return $form;
    }
  }

  /**
   * {@inheritdoc}
   */
  public
  function validateForm(array &$form, FormStateInterface $form_state)
  {
//    if (mb_strlen($form_state->getValue('message')) < 10) {
//      $form_state->setErrorByName('message', $this->t('Message should be at least 10 characters.'));
//    }
  }

  /**
   * {@inheritdoc}
   */
  public
  function submitForm(array &$form, FormStateInterface $form_state)
  {
//    $this->messenger()->addStatus($this->t('The message has been sent.'));
//    $form_state->setRedirect('<front>');
    $nid = $form_state->getValue('nid');
    $uid = $form_state->getValue('uid');
    $node_vote = $form_state->getValue('node_vote');
    $upsert = $this->database->upsert('galicloud_node_votes')
      ->key('nid')
      ->fields(['nid', 'uid', 'vote'])
      ->values([
        'nid' => $nid,
        'uid' => $uid,
        'vote' => $node_vote,
      ])->execute();
    $this->messenger()->addMessage($this->t('Your vote on this node has been registered.'));
  }

}
