galicloud_custom.galicloud_custom_entity_type.*:
  type: config_entity
  label: 'Galicloud custom entity type config'
  mapping:
    id:
      type: string
      label: 'ID'
    label:
      type: label
      label: 'Label'
    uuid:
      type: string
