<?php

/**
 * @file
 * Primary module hooks for Galicloud Events module.
 */

use Drupal\user\UserInterface;
use Drupal\galicloud_events\Event\UserLoginEvent;

/*
* Implements hook_user_login
*/
function galicloud_events_user_login(UserInterface $account)
{
  $event = new UserLoginEvent($account);
  $event_dispatcher = \Drupal::service('event_dispatcher');
  $event_dispatcher->dispatch(UserLoginEvent::USER_LOGIN, $event);
}
