# Schema for the configuration files of the Galicloud Forms module.
galicloud_forms.settings:
  type: config_object
  label: 'Galicloud Forms settings'
  mapping:
    example:
      type: string
      label: 'Example'
