<?php

namespace Drupal\galicloud_forms\Form;

use Drupal\Core\Database\Connection;
use Drupal\Core\Form\ConfirmFormBase;
use Drupal\Core\Form\FormStateInterface;
use Drupal\Core\Url;
use Drupal\node\NodeInterface;
use Symfony\Component\DependencyInjection\ContainerInterface;

/**
 * Provides a confirmation form before clearing out the examples.
 */
class GalicloudConfirmForm extends ConfirmFormBase
{

  protected Connection $database;
  protected $node;

  public function __construct(Connection $database)
  {
    $this->database = $database;
  }

  public static function create(ContainerInterface $container)
  {
    return new static(
      $container->get('database')
    );
//    return parent::create($container); // TODO: Change the autogenerated stub
  }

  /**
   * {@inheritdoc}
   */
  public function getFormId()
  {
    return 'galicloud_forms_example_confirm';
  }

  /**
   * {@inheritdoc}
   */
  public function getQuestion()
  {
    return $this->t('Are you sure you want to delete node "%title" (%nid) from<em>forcontu_node_highlighted</em> table?', ['%title' => $this->node->getTitle(), '%nid' => $this->node->id()]);
  }

  /**
   * {@inheritdoc}
   */
  public function getCancelUrl()
  {
    return new Url('system.admin_config');
  }

  public function buildForm(array $form, FormStateInterface $form_state, NodeInterface $node = null)
  {
    $this->node = $node;
    return parent::buildForm($form, $form_state);
  }

  /**
   * {@inheritdoc}
   */
  public function submitForm(array &$form, FormStateInterface $form_state)
  {
    // @DCG Place your code here.
//    $this->messenger()->addStatus($this->t('Done!'));
//    $form_state->setRedirectUrl(new Url('system.admin_config'));
    $this->database->delete('galicloud_node_highlighted')
      ->condition('nid', $this->node->id())
      ->execute();
    $this->messenger()->addMessage($this->t('The node has been removed.'));
    $form_state->setRedirectUrl($this->getCancelUrl());
  }

}
