<?php

/**
 * @file
 * Primary module hooks for Galicloud pages module.
 */

/**
 * Implements hook_help().
 */
function galicloud_pages_help($route_name, \Drupal\Core\Routing\RouteMatchInterface $route_match)
{
  switch ($route_name) {
    case 'entity.node.edit_form':
      $node = $route_match->getParameter('node');
      $output = '';
      $output .= '<p>' .
        t('Text A. This text is shown in every node edit form. Current node is of type %type and its id is %id', ['%type' => $node->getType(), '%id' => $node->id()]) .
        '</p>';
      if ($node->getType() == 'page') {
        $output .= '<p>' . t('Text B. This text is shown only in Basic pages nodes.') . '</p>';
      }
      return $output;

  }
}

/**
 * Implements hook_toolbar_alter().
 */
function galicloud_pages_toolbar_alter(&$items) {
  $items['administration']['#attached']['library'][] = 'galicloud_pages/galicloud_pages';
}
